name: torch_sp_rsvd_cuda_env
channels:
  - pyg
  - pytorch
  - numba
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=22.1.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - exceptiongroup=1.0.4
  - filelock=3.12.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - icc_rt=2020.2
  - icu=72.1
  - idna=3.4
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.3.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.7.0.149
  - libcurand=10.3.3.53
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libxml2=2.11.4
  - libzlib=1.2.13
  - llvmlite=0.40.1
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=2.8.8
  - numba=0.57.1
  - numpy=1.24.4
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.3
  - pip=23.2
  - platformdirs=3.9.1
  - pluggy=1.0.0
  - pooch=1.7.0
  - pysocks=1.7.1
  - pytest=7.3.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pytz=2023.3
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - six=1.16.0
  - sympy=1.12
  - tbb=2021.9.0
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tomli=2.0.1
  - torchtriton=2.0.0
  - tqdm=4.65.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.40.0
  - xz=5.2.6
  - zlib=1.2.13
