name: tests-conda

on:
#  - push
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda with on ${{ matrix.ubuntu-latest }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reachnes_env
          environment-file: cpu_environment.yml
          auto-activate-base: false
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - run: |
          conda info
          conda list
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install the code as package
        run: python -m pip install -e .
      - name: Run tests
        run: python -m pytest ./tests
